language: clojure
install: sudo rm -rf ~/.lein; mkdir lein; wget -O lein/lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein;
  chmod a+x lein/lein; lein/lein version; export PATH=$PATH:./lein/
script: ./travis-build.sh
jdk:
- oraclejdk8
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: M0XqTcSlJNbQ6zmvtUcyMHDh6VopGvm14epoMQZx3GL6wk+ddcsSaWLsGWt/2BcO1KE8DWnzNaVl24KkDQaGnHtMbpyPePNMDYYkQZG+6XVhcHWkhqymJ8eMOJSnuYlMgu+Xt2rtoq0ULtueV9yMi9nQKhoeERhl76t8UQ3TqPELmzcW96jsfqEU0yOYFiSOfbux99cdlS+vELOq5w7XCEOn4v0bOCMZbM82yYipbFu5ZRj70NMkCX5oQuHXBQ1XcwEH4+aFoCo20AyPN/BsZZ/4k8h14uMNNxuadYHktOFNFnEiD70uVqzgMhOERe45sTB2nb9pIyDs4YuD2kdHLuTwh/bhpqrLN/wAj/eveemlaS+gv79GzB3eyvJxdcPZk/8d+dQzEX0jyKBSUHtSE/xjI20+KB0U9rs/LUNB3bEVJAKJSZXz3uZgSthIbiPfOfIsLRt989A9Vn+pTnSuhOboI4Kcb+EvmEgZYHYgG0BwhXfRSZD29S6uvVmjD3LtfXmUyp7mBlgbkNT0UVodLVth3scrhOmDgQ+CdEniFjqPHO+S2F+H1aGqHoB8zdX9W5K+ANNYBM9BxzB7LtJx1GD0jAYeHj5qseKfC3nMT0e5fne99yhYlLUSTWfCgQBH0E6pdTXmd4+i3iVTTvcAFVpShKAETNEiZwTXWzUTIp0=
  - secure: gs2Gx0cscP/qWhtHOe5BD631gHJa5OZK3WxUmfTxwKRYachEtF6CalaX5Rx+EI2UfE2WHKHZBiozieOhWKWCEBz4VxoOWJeFzX05qWMl2THzS9LirT73j4erMBV5HEfk6ZOPV5xZdteBkMfgrXVKBG3IayasYPlq/RKw7mIjzPy92VuKnMix1XFY1RNJdPpvZ795Gym9ZcaTcA93PsKm/e5ir1F6/flRA1NlFpPjyOb5l76W3NI7x3+10RFghSUTtqK55mpiI3pQH+z/Uac2cRhA3FtBt9mzKxUc1oe5OF7izornE9L5gdeXH6nxUCN9LhfjOZPUa5Ky+QYlt9v/WsJmN99AmrfFW5IRnG3XhXpOH97DdQHIxYCr5GGpZIP15qxk+yY07vZZQZzRG7YvHCPlIzJb3wJCobNOU+/ifGFElAV78fOnK26WoesR8YyrQ39IXJMruF6kplFH4kF+nM+z4/3OYwtGE1PNSncxA+2irb1zry01dq6++6qS8lK2PS9zazNoC0zoOOKm2zTnQkhXZD1nR+d1/aGnuC1whhRcFrKYZc/q9Sobm74sPDjifGNLpizo1Ag/M4SVsSwFqc88+QBzMN1O4q2LN5qBb/K66yXJhoMnyWNeGXYGSF+cYjD4Do32EzGYOA0jKc9E2tijTNb4VqQ1FAjTFjxFCqQ=
  - secure: KxhoT98Co4Hgc12RDHUIgYZ37wgzKdwCamf2yRXV/IeUJ5j/+zmrRgn3KlFJZINsJNuqgfQpKIkHhPBGHloSvTEY+/A4/mOgcP1IIB9DL5PxBVAhFgQp/UC1jylwYIegayfn6iX6YRHZdWYWLPBesWxPjukJ1hCQwddUrcJjGWJfulKVbT8iSgClrOWr1bPTKJWx3gtWodW5Xh0UujKACqk+8ko446dJyXIpAbIA3y4mCXGft0mytZ35SbHxZ0Rl4RGU3OKnZiVESaNp6hEKPFFAQLqZsmYK2fnNvdvXqm8yeoeT8wbh+eW481Ckufta50zjfNgnSXdGJxkf+Bc1OytOhTyBco8Trs8Q9/79uks90+s0KZOTxMYw6Pb9AeMn+4gx2kaRK4yyT7DyPjrOnojMa5HDIjwxUVFGqK4dxKbQU39NwsHbuZmmsV9ZVVPHW2fK4cZ8G9SWD9PZOEvUU7ZYnquAhStk26S3kcH7NSxzJ6rmn6ktiDTOR6OUf8JCFHAGNiMdrD5Zy3mPnpb2f5rT+WsVxuAxLBn9/bhfuVXBqToYEFX2OA2mS/qPiOAZiqj+5nBG0VzT0b31STfMCPXCWw7pDz8GNtyf7XzETmLkRvk8CKaFW8wevnVX6rdYjILqb7GBESZLLY+c815DN/g8Q8YJNETYuGa+IipAiRE=
before_install:
- openssl aes-256-cbc -K $encrypted_8ef97e08c37f_key -iv $encrypted_8ef97e08c37f_iv
  -in atomist_sec.gpg.enc -out atomist_sec.gpg -d
addons:
  apt:
    packages:
    - openssl
    - gnupg
