language: clojure
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - "/\\+travis\\d+$/"
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
  - secure: M0XqTcSlJNbQ6zmvtUcyMHDh6VopGvm14epoMQZx3GL6wk+ddcsSaWLsGWt/2BcO1KE8DWnzNaVl24KkDQaGnHtMbpyPePNMDYYkQZG+6XVhcHWkhqymJ8eMOJSnuYlMgu+Xt2rtoq0ULtueV9yMi9nQKhoeERhl76t8UQ3TqPELmzcW96jsfqEU0yOYFiSOfbux99cdlS+vELOq5w7XCEOn4v0bOCMZbM82yYipbFu5ZRj70NMkCX5oQuHXBQ1XcwEH4+aFoCo20AyPN/BsZZ/4k8h14uMNNxuadYHktOFNFnEiD70uVqzgMhOERe45sTB2nb9pIyDs4YuD2kdHLuTwh/bhpqrLN/wAj/eveemlaS+gv79GzB3eyvJxdcPZk/8d+dQzEX0jyKBSUHtSE/xjI20+KB0U9rs/LUNB3bEVJAKJSZXz3uZgSthIbiPfOfIsLRt989A9Vn+pTnSuhOboI4Kcb+EvmEgZYHYgG0BwhXfRSZD29S6uvVmjD3LtfXmUyp7mBlgbkNT0UVodLVth3scrhOmDgQ+CdEniFjqPHO+S2F+H1aGqHoB8zdX9W5K+ANNYBM9BxzB7LtJx1GD0jAYeHj5qseKfC3nMT0e5fne99yhYlLUSTWfCgQBH0E6pdTXmd4+i3iVTTvcAFVpShKAETNEiZwTXWzUTIp0=
  - secure: gs2Gx0cscP/qWhtHOe5BD631gHJa5OZK3WxUmfTxwKRYachEtF6CalaX5Rx+EI2UfE2WHKHZBiozieOhWKWCEBz4VxoOWJeFzX05qWMl2THzS9LirT73j4erMBV5HEfk6ZOPV5xZdteBkMfgrXVKBG3IayasYPlq/RKw7mIjzPy92VuKnMix1XFY1RNJdPpvZ795Gym9ZcaTcA93PsKm/e5ir1F6/flRA1NlFpPjyOb5l76W3NI7x3+10RFghSUTtqK55mpiI3pQH+z/Uac2cRhA3FtBt9mzKxUc1oe5OF7izornE9L5gdeXH6nxUCN9LhfjOZPUa5Ky+QYlt9v/WsJmN99AmrfFW5IRnG3XhXpOH97DdQHIxYCr5GGpZIP15qxk+yY07vZZQZzRG7YvHCPlIzJb3wJCobNOU+/ifGFElAV78fOnK26WoesR8YyrQ39IXJMruF6kplFH4kF+nM+z4/3OYwtGE1PNSncxA+2irb1zry01dq6++6qS8lK2PS9zazNoC0zoOOKm2zTnQkhXZD1nR+d1/aGnuC1whhRcFrKYZc/q9Sobm74sPDjifGNLpizo1Ag/M4SVsSwFqc88+QBzMN1O4q2LN5qBb/K66yXJhoMnyWNeGXYGSF+cYjD4Do32EzGYOA0jKc9E2tijTNb4VqQ1FAjTFjxFCqQ=
  - secure: KxhoT98Co4Hgc12RDHUIgYZ37wgzKdwCamf2yRXV/IeUJ5j/+zmrRgn3KlFJZINsJNuqgfQpKIkHhPBGHloSvTEY+/A4/mOgcP1IIB9DL5PxBVAhFgQp/UC1jylwYIegayfn6iX6YRHZdWYWLPBesWxPjukJ1hCQwddUrcJjGWJfulKVbT8iSgClrOWr1bPTKJWx3gtWodW5Xh0UujKACqk+8ko446dJyXIpAbIA3y4mCXGft0mytZ35SbHxZ0Rl4RGU3OKnZiVESaNp6hEKPFFAQLqZsmYK2fnNvdvXqm8yeoeT8wbh+eW481Ckufta50zjfNgnSXdGJxkf+Bc1OytOhTyBco8Trs8Q9/79uks90+s0KZOTxMYw6Pb9AeMn+4gx2kaRK4yyT7DyPjrOnojMa5HDIjwxUVFGqK4dxKbQU39NwsHbuZmmsV9ZVVPHW2fK4cZ8G9SWD9PZOEvUU7ZYnquAhStk26S3kcH7NSxzJ6rmn6ktiDTOR6OUf8JCFHAGNiMdrD5Zy3mPnpb2f5rT+WsVxuAxLBn9/bhfuVXBqToYEFX2OA2mS/qPiOAZiqj+5nBG0VzT0b31STfMCPXCWw7pDz8GNtyf7XzETmLkRvk8CKaFW8wevnVX6rdYjILqb7GBESZLLY+c815DN/g8Q8YJNETYuGa+IipAiRE=
  - secure: CG4X2K7gsyhZBEV2XV2U3RdZW3iGvu+JuZ7/+njPl0n+qaXYaYK7sPKlTU5lAUL5HXNgaT1n7AJGVOIt0PNcAkNdl0MSNYg2fnd9zdZrEUpmDuU5MOFKw7L2KQ6ovUThongFo1SLTao8E/jIAFPnI3ccNymZQuV+8+53kUm16hRWywdjt7O7HRIUu60dn5Sz1nUFVJO1Y/j4Ss7MAJ9rRTxNw25JTSbVSdy7OK8E4rTJTpnGcaOTKOqnu8gWg1eRcDzibWOKbB3KPJVgNDmntYT79dx4DfgoRzd6QzUTk3KAISvQmz209dBzCXXDyq9V5yQ+PXx3gctMuzHANxm/YyBSaYjYnKnJQq6UU1fUTjVrR+27PDsYbymd/JmRKNdkB/xxYbckDHAW+hDaGX2kWMBH5r8b7/wES6/IhzIucW+rIw7fPwtFa4i+Yftn4n7udugrLsL5yy6ImkDRyKiqODFixEk36G+4TX8rt2ZilKM2Est+kAGYfZjYRNNy92rKJ0k+gmzcud3GEV2+lYvnzqjzXNORoYfSkFmobdr2PRxAtaLms8nXx7Zed1FPCYBjU14ekPutWbEbz861z41itdoVpIzCmIoZbT18OuNjvRoTNlAL3wj0MWG5fFNCPkFmtquun473qvU1R8rVFWmV5dsGeGGlpfymflZnLV+aYd8=
before_install:
- openssl aes-256-cbc -K $encrypted_8ef97e08c37f_key -iv $encrypted_8ef97e08c37f_iv
  -in atomist_sec.gpg.enc -out atomist_sec.gpg -d
addons:
  apt:
    packages:
    - openssl
    - gnupg
deploy:
  provider: releases
  api_key:
    secure: u9dLx6tEVbEvz4HTCSLokps/h1UiTb15pBdz8PxZt+SHhutnBo9rPwWNtHt5gQ2nljorU99UlXNcnzTy9n2faBS3ZfaBaMhhURTyzrYyg4cvjvNTe41+r+P5a4GR71GQFjivdjj1jCu0qzPz/INO9E+ZovJ7nNXa+0iTrVDvGR33HkxHOe0DHGH5ru3XTe8NQMHBQe0AXPyXQ7nilB6h+6+76gf+faENDQx1KZ6P8r15e75WtJwofaT8DZZ+Ey9Q4pOobK3eWUID5mKuYDweOHSYW6q559twqj75ZdCQIowm/usCg9RINM/MZze0aM47ntHUBjaLpLw+0eOqP2dBaqMIN/oVzZtKOOb1ABu9kafDf6YSE3kcCbtu7ocDPl6b0JeUy1YKNecKeSOJTxN49Kbj2JMIfC+7pvs/lp25UERXga21nb2+p6d6ih5OIBFz8WpXhWoPUIMW5Stf6emNCbo3Xdyp0wYGssDtJw0fTeHZ15mbGw/cKfgGW3wssGgAEysm/M9RNDfCUKmLN22H3r1YQgy6eP0uKiXxU98RSaM0b7AIjfVpmqeekthFZUFXsOW0GP/CPM8doZrXVlhs7xKztzxhyDFNmjMgTDL4CtKtsa0UPlj6894U+7MFm7oWfxtZIuO5YHb15czT1J44303YkdHt6BA+AcBGCbIXPY8=
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
